SET DATABASE SQL SYNTAX DB2 TRUE;
SET DATABASE TRANSACTION CONTROL MVCC;

DROP SCHEMA PUBLIC CASCADE

CREATE TABLE PERSON
(
  ID_PERSON BIGINT NOT NULL,
  NAME CHAR(50) NOT NULL,
  LASTNAME CHAR(50) NOT NULL,
  AGE SMALLINT NOT NULL,
  CONSTRAINT IP_Person PRIMARY KEY (ID_PERSON)
)

COMMENT ON TABLE PERSON IS 'Almacena datos de personas.';
